CREATE TABLE IF NOT EXISTS "public"."OnlineGames" (
    "online_game_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "owner_user_id" uuid NOT NULL REFERENCES "auth"."users"("id") ON DELETE CASCADE,
    "status" text NOT NULL DEFAULT 'in_progress'
        CHECK ("status" IN ('in_progress', 'completed', 'abandoned')),
    "ruleset" jsonb NOT NULL,
    "seats" jsonb NOT NULL,
    "state" jsonb NOT NULL,
    "scores" jsonb NOT NULL,
    "hand_number" integer NOT NULL DEFAULT 1,
    "version" integer NOT NULL DEFAULT 1,
    "created" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."OnlineGames" OWNER TO "postgres";

CREATE INDEX "OnlineGames_owner_status_idx"
    ON "public"."OnlineGames" ("owner_user_id", "status");

COMMENT ON TABLE "public"."OnlineGames" IS
  'Server-authoritative snapshots for authenticated online games. Hidden state must never be returned directly.';

CREATE POLICY "Full Access for postgres user" ON "public"."OnlineGames"
    TO "postgres" USING (true) WITH CHECK (true);

ALTER TABLE "public"."OnlineGames" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."OnlineGames" TO "anon";
GRANT ALL ON TABLE "public"."OnlineGames" TO "authenticated";
GRANT ALL ON TABLE "public"."OnlineGames" TO "service_role";
GRANT ALL ON SEQUENCE "public"."OnlineGames_online_game_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."OnlineGames_online_game_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."OnlineGames_online_game_id_seq" TO "service_role";

CREATE TABLE IF NOT EXISTS "public"."OnlineGameActions" (
    "online_game_action_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "online_game_id" bigint NOT NULL
        REFERENCES "public"."OnlineGames"("online_game_id") ON DELETE CASCADE,
    "seq" integer NOT NULL,
    "seat" smallint NOT NULL,
    "action" jsonb NOT NULL,
    "created" timestamp with time zone DEFAULT "now"() NOT NULL,
    UNIQUE ("online_game_id", "seq")
);

ALTER TABLE "public"."OnlineGameActions" OWNER TO "postgres";

CREATE INDEX "OnlineGameActions_game_idx"
    ON "public"."OnlineGameActions" ("online_game_id", "seq");

COMMENT ON TABLE "public"."OnlineGameActions" IS
  'Append-only debug/replay log. OnlineGames.state remains the source of truth.';

CREATE POLICY "Full Access for postgres user" ON "public"."OnlineGameActions"
    TO "postgres" USING (true) WITH CHECK (true);

ALTER TABLE "public"."OnlineGameActions" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."OnlineGameActions" TO "anon";
GRANT ALL ON TABLE "public"."OnlineGameActions" TO "authenticated";
GRANT ALL ON TABLE "public"."OnlineGameActions" TO "service_role";
GRANT ALL ON SEQUENCE "public"."OnlineGameActions_online_game_action_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."OnlineGameActions_online_game_action_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."OnlineGameActions_online_game_action_id_seq" TO "service_role";
