


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."Player Role" AS ENUM (
    'Picker',
    'Partner',
    'Opponent',
    'Leaster Winner',
    'Leaster Loser'
);


ALTER TYPE "public"."Player Role" OWNER TO "postgres";


COMMENT ON TYPE "public"."Player Role" IS 'Picker, Partner, Opponent, Leaster';



CREATE TYPE "public"."Round Result" AS ENUM (
    'Picker Win',
    'Picker Loss',
    'Opponent Win',
    'Opponent Loss',
    'Leaster'
);


ALTER TYPE "public"."Round Result" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Games" (
    "game_id" bigint NOT NULL,
    "game_datetime" timestamp without time zone,
    "created" timestamp with time zone DEFAULT "now"() NOT NULL,
    "num_players" smallint,
    "is_completed" boolean DEFAULT false NOT NULL,
    CONSTRAINT "Games_num_players_check" CHECK ((("num_players" = 3) OR ("num_players" = 5)))
);


ALTER TABLE "public"."Games" OWNER TO "postgres";


ALTER TABLE "public"."Games" ALTER COLUMN "game_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Games_game_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."PlayerRoundScore" (
    "player_round_score_id" bigint NOT NULL,
    "created" timestamp with time zone DEFAULT "now"() NOT NULL,
    "round_id" bigint NOT NULL,
    "player_id" bigint NOT NULL,
    "point_delta" integer NOT NULL,
    "player_role" "public"."Player Role" NOT NULL
);


ALTER TABLE "public"."PlayerRoundScore" OWNER TO "postgres";


ALTER TABLE "public"."PlayerRoundScore" ALTER COLUMN "player_round_score_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."PlayerRoundScore_player_round_score_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Players" (
    "player_id" bigint NOT NULL,
    "created" timestamp with time zone DEFAULT "now"() NOT NULL,
    "player_name" character varying NOT NULL
);


ALTER TABLE "public"."Players" OWNER TO "postgres";


COMMENT ON TABLE "public"."Players" IS 'Players of a game';



CREATE TABLE IF NOT EXISTS "public"."Players_X_Games" (
    "playerXgame_id" bigint NOT NULL,
    "player_id" bigint NOT NULL,
    "game_id" bigint NOT NULL,
    "created" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."Players_X_Games" OWNER TO "postgres";


ALTER TABLE "public"."Players_X_Games" ALTER COLUMN "playerXgame_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Players_X_Games_playerXgame_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."Players" ALTER COLUMN "player_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Players_player_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Rounds" (
    "round_id" bigint NOT NULL,
    "game_id" bigint NOT NULL,
    "round_number" smallint NOT NULL,
    "created" timestamp with time zone DEFAULT "now"() NOT NULL,
    "round_result" "public"."Round Result" NOT NULL,
    "no_schneider" boolean,
    "no_trick" boolean,
    "no_partner" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."Rounds" OWNER TO "postgres";


ALTER TABLE "public"."Rounds" ALTER COLUMN "round_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Rounds_round_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Users" (
    "user_id" bigint NOT NULL,
    "username" character varying NOT NULL,
    "password_hash" character varying NOT NULL,
    "created" timestamp with time zone DEFAULT "now"() NOT NULL,
    "permission_level" smallint DEFAULT '1'::smallint
);


ALTER TABLE "public"."Users" OWNER TO "postgres";


ALTER TABLE "public"."Users" ALTER COLUMN "user_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Users_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Games"
    ADD CONSTRAINT "Games_pkey" PRIMARY KEY ("game_id");



ALTER TABLE ONLY "public"."PlayerRoundScore"
    ADD CONSTRAINT "PlayerRoundScore_pkey" PRIMARY KEY ("player_round_score_id");



ALTER TABLE ONLY "public"."Players_X_Games"
    ADD CONSTRAINT "Players_X_Games_pkey" PRIMARY KEY ("playerXgame_id");



ALTER TABLE ONLY "public"."Players"
    ADD CONSTRAINT "Players_pkey" PRIMARY KEY ("player_id");



ALTER TABLE ONLY "public"."Rounds"
    ADD CONSTRAINT "Rounds_pkey" PRIMARY KEY ("round_id");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."PlayerRoundScore"
    ADD CONSTRAINT "PlayerRoundScore_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."Players"("player_id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."PlayerRoundScore"
    ADD CONSTRAINT "PlayerRoundScore_round_id_fkey" FOREIGN KEY ("round_id") REFERENCES "public"."Rounds"("round_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Players_X_Games"
    ADD CONSTRAINT "Players_X_Games_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."Games"("game_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Players_X_Games"
    ADD CONSTRAINT "Players_X_Games_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."Players"("player_id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."Rounds"
    ADD CONSTRAINT "Rounds_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."Games"("game_id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Full Access for postgres user" ON "public"."PlayerRoundScore" TO "postgres" USING (true);



CREATE POLICY "Full Access for postgres user" ON "public"."Players" TO "postgres" USING (true);



CREATE POLICY "Full Access for postgres user" ON "public"."Players_X_Games" TO "postgres" USING (true);



CREATE POLICY "Full Access for postgres user" ON "public"."Rounds" TO "postgres" USING (true);



CREATE POLICY "Full Access for postgress user" ON "public"."Games" TO "postgres" USING (true);



ALTER TABLE "public"."Games" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."PlayerRoundScore" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Players" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Players_X_Games" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Rounds" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "anon";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "service_role";


















GRANT ALL ON TABLE "public"."Games" TO "anon";
GRANT ALL ON TABLE "public"."Games" TO "authenticated";
GRANT ALL ON TABLE "public"."Games" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Games_game_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Games_game_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Games_game_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."PlayerRoundScore" TO "anon";
GRANT ALL ON TABLE "public"."PlayerRoundScore" TO "authenticated";
GRANT ALL ON TABLE "public"."PlayerRoundScore" TO "service_role";



GRANT ALL ON SEQUENCE "public"."PlayerRoundScore_player_round_score_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."PlayerRoundScore_player_round_score_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."PlayerRoundScore_player_round_score_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Players" TO "anon";
GRANT ALL ON TABLE "public"."Players" TO "authenticated";
GRANT ALL ON TABLE "public"."Players" TO "service_role";



GRANT ALL ON TABLE "public"."Players_X_Games" TO "anon";
GRANT ALL ON TABLE "public"."Players_X_Games" TO "authenticated";
GRANT ALL ON TABLE "public"."Players_X_Games" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Players_X_Games_playerXgame_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Players_X_Games_playerXgame_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Players_X_Games_playerXgame_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Players_player_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Players_player_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Players_player_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Rounds" TO "anon";
GRANT ALL ON TABLE "public"."Rounds" TO "authenticated";
GRANT ALL ON TABLE "public"."Rounds" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Rounds_round_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Rounds_round_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Rounds_round_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Users" TO "anon";
GRANT ALL ON TABLE "public"."Users" TO "authenticated";
GRANT ALL ON TABLE "public"."Users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Users_user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Users_user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Users_user_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";



































